/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example uuid-1234 */
            id: string;
            /** @example user@example.com */
            email: string;
            /** @example Taro */
            name: string;
        };
        QGroup: {
            /** @example uuid-5678 */
            id: string;
            /** @example 数学 */
            title: string;
            /** @example abc123 */
            passphrase: string;
        };
        Question: {
            /** @example uuid-1111 */
            id: string;
            /** @example uuid-5678 */
            qgroupId: string;
            /** @example 3 */
            index: number;
            /** @example 次の計算をせよ */
            description: string;
            /** @example 42 */
            correctAnswer: string;
        };
        Trial: {
            /** @example uuid-2222 */
            id: string;
            /** @example uuid-5678 */
            qgroupId: string;
            /** @example uuid-1234 */
            userId: string;
            /** @example 1 */
            index: number;
            /**
             * Format: date-time
             * @example 2024-01-01T10:00:00Z
             */
            startTime: string;
        };
        Answer: {
            /** @example uuid-3333 */
            id: string;
            /** @example uuid-2222 */
            trialId: string;
            /** @example uuid-1111 */
            questionId: string;
            /** @example 42 */
            answer: string;
            /** @example 5 */
            score: number;
            /** @example done */
            scoringStatus?: string | null;
            /** @example 丁寧に書かれていた */
            memo: string;
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @example VALIDATION_ERROR */
                code?: string;
                /** @example メール形式が不正です */
                message?: string;
                details?: Record<string, never>;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
